application/frontend/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views


urlpatterns = [
    path('', HomePage.as_view(), name='homepage'),
    path('pricing', Pricing.as_view(), name='pricing'),
    path('education/package', EducationView.as_view(), name='education'),
    path('register/<package_id>/<modules>', RegisterProduct.as_view(), name='register_product'),
    path('module_detail/<product_id>', ProductDetail.as_view(), name='product_detail'),
    path('process/<package_id>', process_modular, name='process_modular'),
    path('demo_form/<package_id>', demo_view, name='demo_view'),

    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('login_redirect/', login_redirect, name='login_redirect'),

    # path('account/forgot-password', Login.as_view(), name='login'),

]

payloop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.frontend.urls')),
    path('', include('apps.backend.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

admin.site.site_header = "PayLoop Admin Portal"
admin.site.site_title = "PayLoop Admin Portal"
admin.site.index_title = "Welcome to PayLoop Super User Portal"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/backend/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
# Create your models here.


Category = (
    (1, 'Payloop'),
    (2, 'Education')
)


class Product(models.Model):
    category = models.IntegerField(choices=Category, default=1)
    name = models.CharField(max_length=50)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    icon = models.ImageField(upload_to='product_icons')
    content = RichTextField()
    video = models.CharField(max_length=20)
    gallery1 = models.ImageField(upload_to='gallery_images')
    gallery2 = models.ImageField(upload_to='gallery_images', blank=True, null=True)
    gallery3 = models.ImageField(upload_to='gallery_images', blank=True, null=True)
    gallery4 = models.ImageField(upload_to='gallery_images', blank=True, null=True)

    class Meta:

        verbose_name_plural = 'Products'
        verbose_name = 'Product'

    def __str__(self):

        return self.name


class Packages(models.Model):
    PackageType = (
        (1, 'All Package'),
        (2, 'Custom'),
        (3, 'Single Package'),
    )

    name = models.CharField(max_length=10)
    p_type = models.IntegerField(choices=PackageType)
    des = models.TextField()

    class Meta:
        verbose_name_plural = 'Packages'
        verbose_name = 'Packages'

    def __str__(self):

        return self.name


class ClientProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    company_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    address = models.TextField()
    package = models.ForeignKey(Packages, on_delete=models.CASCADE)
    modules = models.CharField(max_length=50, blank=True, null=True)
    reg_date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Clients Profile'
        verbose_name = 'Client Profile'

    def __str__(self):

        return self.user.get_full_name()


class BannerText(models.Model):
    title = models.CharField(max_length=254)
    highlight = models.CharField(max_length=254)
    content = models.TextField()
    activate = models.BooleanField()


class UserType(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_staff = models.BooleanField()


class DemoList(models.Model):
    DemoType = (
        ('education', 'Education Modules'),
        ('ERP', 'Enterprise Resource Planning'),

    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=50)
    email = models.EmailField()
    company_name = models.CharField(max_length=50)
    company_address = models.TextField()
    demo_type = models.CharField(choices=DemoType, max_length=10)


class Education(models.Model):
    name = models.CharField(max_length=50)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    icon = models.ImageField(upload_to='product_icons')
    content = RichTextField()
    video = models.CharField(max_length=20)
    gallery1 = models.ImageField(upload_to='gallery_images', blank=True, null=True)
    gallery2 = models.ImageField(upload_to='gallery_images', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Education Products'
        verbose_name = 'Education Product'

    def __str__(self):
        return self.name


class ClientModule(models.Model):
    MODULE_TYPE = (
        ('erp', 'ERP'),
        ('education', 'Education')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    module = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    education = models.ForeignKey(Education, on_delete=models.CASCADE, null=True)
    module_type = models.CharField(choices=MODULE_TYPE, default=MODULE_TYPE[0][0], max_length=12)
    last_pay_date = models.DateField(null=True, blank=True)
    next_pay_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    suspend = models.BooleanField(default=False)

application/frontend/models.py
from django.db import models

# Create your models here.

application/frontend/forms.py
from django import forms
from ..backend.models import ClientProfile, DemoList
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import TextInput


#  Login form inheriting from Django Authentication Form
class LoginForm(AuthenticationForm):
    username = forms.CharField(required=True, widget=TextInput(attrs={'class': 'form-control',
                                                                      'type': 'text', 'id': 'username',
                                                                      'placeholder': 'Enter Username'}))
    password = forms.CharField(required=True, widget=TextInput(attrs={'class': 'form-control',
                                                                      'type': 'password', 'id': 'password',
                                                                      'placeholder': 'Enter Password'}))


class RegisterProductForm(forms.ModelForm):

    class Meta:

        model = ClientProfile
        exclude = ['user', 'package', 'expiry_date', 'reg_date', 'last_pay_date', 'next_pay_date', 'modules']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })
        self.fields['phone'].widget.attrs.update({'type': 'number'})


class DemoForm(forms.ModelForm):

    class Meta:
        model = DemoList
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
            })

application/frontend/views.py
from django.views import generic
from ..backend.models import Packages, BannerText, Product, ClientProfile, UserType, ClientModule, Education
from .forms import RegisterProductForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.db import transaction
from .forms import LoginForm, DemoForm, DemoList
from ..base import send_welcome_email, send_notification


# Create your views here.


def login_redirect(request):
    user_id = request.user.id
    try:
        is_staff = UserType.objects.get(user_id=user_id).is_staff
        if is_staff is True:
            return redirect('dashboard')
        else:
            customer_pk = ClientProfile.objects.get(user_id=request.user.id).pk
            return redirect('customer_profile', customer_pk)
            pass
    except UserType.DoesNotExist:
        messages.error(request, 'System Error!...UserType does not exist')
        return redirect('login')


class Login(generic.FormView):
    template_name = 'registration/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('login')


class HomePage(generic.TemplateView):
    template_name = 'frontend/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['packages'] = Packages.objects.all()
        try:
            context['banner_text'] = BannerText.objects.get(activate=True)
        except BannerText.DoesNotExist:
            pass
        context['erp'] = Product.objects.filter(category=1)
        context['edu'] = Product.objects.filter(category=2)
        context['products'] = Product.objects.all()
        context['form'] = DemoForm
        return context


class Pricing(generic.TemplateView):
    template_name = 'frontend/pricing.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['packages'] = Packages.objects.all()
        return context


class ProductDetail(generic.DetailView):
    template_name = 'frontend/inventory.html'
    model = Product
    pk_url_kwarg = 'product_id'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = DemoForm
        return context


class RegisterProduct(generic.FormView):
    template_name = 'frontend/register_product.html'
    form_class = RegisterProductForm

    def get_success_url(self):
        return reverse_lazy('register_product', kwargs={'package_id': self.kwargs['package_id'],
                                                        'modules': self.kwargs['modules']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        package = Packages.objects.get(id=self.kwargs['package_id'])

        s_modules = self.kwargs['modules']
        if s_modules == 'custom':
            context['s_modules'] = None
        elif s_modules == 'no-module':
            context['s_modules'] = 'None Selected'
        elif s_modules == 'all_package':
            all_module = []
            payable = 0
            modules = Product.objects.all()
            for item in modules:
                all_module.append(item.id)
                amount = Product.objects.get(id=item.id).amount
                payable += amount
            context['s_modules'] = list(map(int, all_module))
            context['product'] = Product.objects.all()
            context['payable'] = payable
        elif s_modules == 'education':
            package.name = 'Educational Module'
            payable = 0
            all_module = []
            modules = Product.objects.filter(category=2)
            for item in modules:
                all_module.append(item.id)
                amount = Product.objects.get(id=item.id).amount
                payable += amount
            context['payable'] = payable
            context['product'] = modules
            all_module = []
            modules = Product.objects.all()
            for item in modules:
                all_module.append(item.id)
            context['s_modules'] = list(map(int, all_module))

        else:
            s_modules = list(self.request.session.get('s_module', ''))
            payable = 0
            for element in s_modules:
                if element == ',':
                    s_modules.remove(element)
            for element in s_modules:
                amount = Product.objects.get(id=int(element)).amount
                payable += amount

            results = list(map(int, s_modules))
            context['payable'] = payable
            context['s_modules'] = results
            context['product'] = Product.objects.all()
        context['package'] = package
        return context

    @staticmethod
    def generate_username(first_name, last_name):
        val = "{0}{1}".format(first_name[0], last_name).lower()
        x = 0
        while True:
            if x == 0 and User.objects.filter(username=val).count() == 0:
                return val
            else:
                new_val = "{0}{1}".format(val, x)
                if User.objects.filter(username=new_val).count() == 0:
                    return new_val
            x += 1
            if x > 1000000:
                raise Exception("Name is super popular!")

    def form_valid(self, form):
        if self.request.method == 'POST':
            f_name = self.request.POST['first_name']
            l_name = self.request.POST['last_name']
            email = self.request.POST['email']
            company_name = self.request.POST['company_name']
            phone = self.request.POST['phone']
            address = self.request.POST['address']

            username = self.generate_username(f_name, l_name)
            password = User.objects.make_random_password()
            with transaction.atomic():
                user = User.objects.create_user(
                    username=username,
                    first_name=f_name,
                    last_name=l_name,
                    email=email,
                    password=password
                )
                user.save()
                user_type = UserType.objects.create(
                    user=user,
                    is_staff=False
                )
                user_type.save()

                s_modules = self.kwargs['modules']
                package = Packages.objects.get(id=self.kwargs['package_id'])
                if s_modules == 'custom':
                    new_profile = ClientProfile.objects.create(
                        user=user,
                        phone=phone,
                        address=address,
                        package_id=package.id,
                        company_name=company_name
                    )
                elif s_modules == 'no-module':
                    new_profile = ClientProfile.objects.create(
                        user=user,
                        phone=phone,
                        address=address,
                        package_id=package.id,
                        company_name=company_name
                    )
                elif s_modules == 'all_package':
                    product = Product.objects.all()
                    for item in product:
                        client_modules = ClientModule.objects.create(
                            user=user,
                            module_id=item.id,

                        )
                        client_modules.save()
                    new_profile = ClientProfile.objects.create(
                        user=user,
                        phone=phone,
                        address=address,
                        package_id=package.id,
                        company_name=company_name,
                    )
                elif s_modules == 'education':
                    product = Product.objects.filter(category=2)
                    for item in product:
                        client_modules = ClientModule.objects.create(
                            user=user,
                            module_id=item.id,
                        )
                        client_modules.save()
                    new_profile = ClientProfile.objects.create(
                        user=user,
                        phone=phone,
                        address=address,
                        package_id=package.id,
                        company_name=company_name,
                    )

                else:
                    s_modules = list(self.request.session.get('s_module', ''))
                    s_modules = list(s_modules)
                    for element in s_modules:
                        if element == ',':
                            s_modules.remove(element)
                    for element in s_modules:
                        try:
                            Product.objects.get(id=int(element))
                            client_modules = ClientModule.objects.create(
                                user=user,
                                module_id=element,
                            )
                            client_modules.save()
                        except KeyError:
                            pass

                    new_profile = ClientProfile.objects.create(
                        user=user,
                        phone=phone,
                        address=address,
                        package_id=package.id,
                        company_name=company_name,
                    )
                new_profile.save()

            send_welcome_email(user.id, password)
            send_notification(user.id)
            messages.success(self.request, 'Your registration was successful.. Please check your email for more '
                                           'instructions')
        return super().form_valid(form)


def process_modular(request, package_id):
    form_post = request.POST
    module = []

templates/frontend/Forgot_password.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block main_page %}
    <section class="login">
            <div class="auto-container">
                <div class="m-auto col-md-9 login-box p0">
                    <div class="left-block col-md-6 col-sm-6 col-xs-12 p0">
                        <img src="http://payloop.net/usertheme/images/login.jpg" alt="" width="100%">
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12">

						<form action="http://payloop.net/Forgot_password" method="POST" role="form" class="default-form" accept-charset="utf-8">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <img src="http://payloop.net/usertheme/images/logo.png" alt="">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Please enter your email address we'll send you instruction on how to reset password</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group mtb">
                                        <label>Your Email</label>
                                        <input type="text" name="email" class="form-control">
                                        <span class="error" style="display:block !important;"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group "><button type="submit" class="theme-btn btn-style-two">Send</button></div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group mb-xs-0">
                                        <div class="pull-left"><a href="http://payloop.net/Login">Back to login</a></div>
                                    </div>
                                </div>
                            </div>
                       </form>                    </div>
                </div>
            </div>
        </section>
{% endblock main_page %}

templates/frontend/Inventory.html
{% extends 'frontend/base.html' %}
{% load static %}
{% block page_css  %}
    <style>
    .video-container {
        position: relative;
        padding-bottom: 56.25%;
        padding-top: 30px; height: 0; overflow: hidden;
        }

        .video-container iframe,
        .video-container object,
        .video-container embed {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        }
    </style>
{% endblock page_css %}

{% block main_page %}

        {% block menu1 %} {% endblock %}
        <section class="product-banner crm">
            <div class="auto-container text-center">
                <h3>Payloop Enterprise Resource Planning</h3>
                <p>{{ object.name }} Module</p>
                <a href="{% url 'homepage' %}#pricing"><button class="btn btn-theme1">Start Now</button></a>
                <button class="btn btn-theme1 outline" data-toggle="modal" data-target="#demoModal">Schedule A Demo</button>

            </div>
        </section>
        {% if messages %}
            {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <span style="margin-left: 10px">{{ message }}</span>
                    </div>
            {% endfor %}
        {% endif %}
        {% if form.errors %}
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span style="margin-left: 10px">{{ form.errors }}</span>
            </div>
        {% endif %}
        <section class="product-detail">
            <div class="auto-container">
                <div class="por fb image-block">
                    <img src="{{ object.gallery1.url }}" alt="{{ object.name }}">
                    <img src="{{ object.gallery1.url }}" alt="{{ object.name }}" class="abs">
                </div>
            </div>
        </section>
        <div class="product-intro">
            <div class="auto-container">
                <div class="row">
                    <div class="col-md-6">
                        <h3>{{ object.name }} Module</h3>
                        <p>
                            {{ object.content|safe }}
                        </p>
                    </div>
                    <div class="col-md-6 video-container" style="padding-top: 0!important; padding-bottom: 25.25%;">

                        <style>
                            .embed-container
                                { position: initial; padding-bottom: 60%; height: 0;  max-width: 100%; }
                            .embed-container iframe,
                            .embed-container object,
                            .embed-container embed
                                { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }
                        </style>

                        <div class='embed-container'>
                            <iframe src='https://www.youtube.com/embed/{{ object.video }}' frameborder='0' allowfullscreen></iframe>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!--Modal -->
                <div class="modal fade" id="demoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Please complete our demo form</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                        <form method="post" action="{% url 'demo_view' object.id %}">
                            {% csrf_token %}
                            <div class="modal-body">
                                  <div class="form-group">
                                        {{ form }}
                                  </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Save changes</button>
                            </div>
                        </form>

                    </div>
                  </div>
                </div>

                <!-- End Modal -->
{% endblock main_page %}

templates/frontend/pricing.html
{% extends 'frontend/base.html' %}
{% load static %}

{% block main_page %}
    <section class="product-banner services">
        <div class="auto-container text-center">
            <h3>Pricing</h3>
            <p>Something nice is coming here</p>
        </div>
    </section>

    <section>
        <div class="pricing-wrapper clearfix">

            {% for package in packages %}
                <div class="pricing-table">
                    <h3 class="pricing-title">{{ package.name }}</h3>
                    <div class="price">₦60<sup>/ module</sup></div>
                    <ul class="table-list">
                        <li>Item 1 <span>Something Nice</span></li>
                    </ul>
                    <div class="table-buy">
                        <a href="{% url 'register_product' package.id %}" class="pricing-action">Buy Now</a>
                    </div>
                </div>
            {% endfor %}


        </div>
    </section>

{% endblock main_page %}



templates/frontend/register_product.html
{% extends 'frontend/base.html' %}
{% load static %}
{% load humanize %}

{% block main_page %}
    {% block menu1 %} {% endblock %}

    <section class="product-banner services">
        <div class="auto-container text-center">
            <h2 style="color: whitesmoke">Selected Package </h2>
            <h3>{{ package.name }}</h3>
            <h3>NGN {{ payable|intcomma }}</h3>


        </div>
    </section>

    <section class="pad pad-big four-circle three-divided">
        <div class="auto-container">
            <div class="title-tag">
                <h3><span class="clr">Selected Modules</span></h3>
            </div>
            <div class="row df">
                {% for item in product %}
                    {% for s in s_modules %}
                        {% if item.id == s %}
                            <div class="col-xs-12 col-md-4 col-sm-6 three-divide">
                                <div class="col-xs-6 circle-block"></div>
                                <p>{{ item.name }}</p> <br />
                                <img style="max-width: 50px" src="{{ item.icon.url }}" />
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    </section>

    <section class="contact-section">
        <div class="auto-container">
            <div class="row clearfix">
                <div class="form-column col-md-6 col-md-offset-3 col-sm-12 col-xs-12">
                    {% if messages %}
                        {% for message in messages %}
                                <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <span style="margin-left: 10px">{{ message }}</span>
                                </div>
                        {% endfor %}
                    {% endif %}
                    {% if form.errors %}
                        <div class="alert alert-danger alert-dismissible">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <span style="margin-left: 10px">{{ form.errors }}</span>
                        </div>
                    {% endif %}
                    <div class="sec-title">
                        <h2 data-aos="fade-up" data-aos-delay="150">Please complete your registration</h2>
                    </div>
                    <div class="default-form contact-form">
                        <form method="post" id="contact-form">
                            {% csrf_token %}
                            <p>
                                <label for="f_name">First name:</label>
                                <input type="text" name="first_name" maxlength="50" class="form-control" required id="id_first_name">
                            </p>
                            <p>
                                <label for="l_name">Last name:</label>
                                <input type="text" name="last_name" maxlength="50" class="form-control" required id="id_last_name">
                            </p>
                            {{ form.as_p }}
                            <button type="submit" class="theme-btn btn-style-two">Submit Form</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock main_page %}